//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.DocVerifier.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2.DocVerifier.Services.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIKey.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagePath.
        /// </summary>
        internal static string ConfiguredImagePath {
            get {
                return ResourceManager.GetString("ConfiguredImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \wwwroot\images\.
        /// </summary>
        internal static string ContentImagePath {
            get {
                return ResourceManager.GetString("ContentImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpeg.
        /// </summary>
        internal static string DestinationImageFileExtension {
            get {
                return ResourceManager.GetString("DestinationImageFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and analyze multiple documents within the provided file, process their content, extract relevant data, generate a structured hierarchical JSON use response template {&quot;documentType&quot;:&quot;&quot;,&quot;pageNumber&quot;:0,&quot;confidenceScore&quot;:0,&quot;isFraudDocument&quot;:&quot;boolean&quot;,&quot;isReissued&quot;:&quot;boolean&quot;,&quot;imageWidth&quot;:0,&quot;imageHeight&quot;:0,&quot;aspectRatio&quot;:0,&quot;imageResolutionX&quot;:0,&quot;imageResolutionY&quot;:0,&quot;elements&quot;:[{&quot;label&quot;:&quot;&quot;,&quot;value&quot;:&quot;&quot;,&quot;confidence_score&quot;:0,&quot;isFraudValue&quot;:&quot;boolean&quot;,&quot;x&quot;:0,&quot;y&quot;:0,&quot;height&quot;:0,&quot;width&quot;:0}]} format for each document. Com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocDataPrompt {
            get {
                return ResourceManager.GetString("DocDataPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocVerifierEndPoint.
        /// </summary>
        internal static string DocVerifierEndPoint {
            get {
                return ResourceManager.GetString("DocVerifierEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMddHHmmss.
        /// </summary>
        internal static string FileNameDateTimeFormat {
            get {
                return ResourceManager.GetString("FileNameDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _mapped.
        /// </summary>
        internal static string FinalImageMappedPrefix {
            get {
                return ResourceManager.GetString("FinalImageMappedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/.
        /// </summary>
        internal static string ImageFileAbsolutePath {
            get {
                return ResourceManager.GetString("ImageFileAbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_.
        /// </summary>
        internal static string ImageFilePrefix {
            get {
                return ResourceManager.GetString("ImageFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        internal static string PDFFileExtension {
            get {
                return ResourceManager.GetString("PDFFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract each element and return box data in x, y, width and height.
        /// </summary>
        internal static string PlottingPrompt {
            get {
                return ResourceManager.GetString("PlottingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string ResponseMimeType {
            get {
                return ResourceManager.GetString("ResponseMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and analyze multiple documents within the provided file, process their content, extract relevant data, generate a structured hierarchical JSON use response template {&quot;documentType&quot;:&quot;&quot;,&quot;pageNumber&quot;:0,&quot;confidenceScore&quot;:0,&quot;isFraudDocument&quot;:&quot;boolean&quot;,&quot;isReissued&quot;:&quot;boolean&quot;,&quot;imageWidth&quot;:0,&quot;imageHeight&quot;:0,&quot;aspectRatio&quot;:0,&quot;imageResolutionX&quot;:0,&quot;imageResolutionY&quot;:0,&quot;elements&quot;:{&quot;employee_social_security_number&quot;:{&quot;value&quot;:&quot;&quot;,&quot;confidence_score&quot;:0,&quot;isFraudValue&quot;:&quot;boolean&quot;,&quot;x&quot;:0,&quot;y&quot;:0,&quot;height&quot;:0,&quot;width&quot;:0},&quot;employe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidatorPrompt {
            get {
                return ResourceManager.GetString("ValidatorPrompt", resourceCulture);
            }
        }
    }
}
